name: Build
on:
  push:
    branches:
      - master
env:
  CC: clang
  CXX: clang++
  LLVM_PATH: ./llvm
  LLVM_VERSION: 16
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache LLVM
        uses: actions/cache@v3
        id: cache-llvm
        with:
          path: ${{ env.LLVM_PATH }}
          key: ${{ runner.os }}-llvm-${{ env.LLVM_VERSION }}
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Cache CMake build folder
        uses: actions/cache@v3
        with:
          path: cmake-build*/
          key: ${{ runner.os }}-${{ github.job }}-${{ matrix.config }}
      - name: Init CMake
        run: cmake -B cmake-build
      - name: Build
        run: cmake --build cmake-build --target cpr_hello_world
      - name: Run
        run: cmake-build/bin/cpr_hello_world
